type WeeklyReportProps = {
  title: string
  periodStart?: string
  periodEnd?: string
}

export function renderWeeklyReport(props: WeeklyReportProps) {
  return `
    <html>
      <body style="font-family: Arial, sans-serif; color: #333333; padding: 24px;">
        <header style="display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #6DBE45;padding-bottom:8px;">
          <h1 style="color:#1B2D4F;margin:0;">${props.title}</h1>
          <span>${new Date().toISOString().slice(0, 10)}</span>
        </header>
        <p>Period: ${props.periodStart ?? "-"} to ${props.periodEnd ?? "-"}</p>
        <h2 style="color:#1B2D4F;border-bottom:2px solid #6DBE45;">Week Summary</h2>
        <p>Weekly summary generated by Jolene.</p>
      </body>
    </html>
  `
}
